### ISSUE TITLE
ModuleNotFoundError: No module named 'pycares._cares' (py 3.7)

### ISSUE THREAD

**Issue by mdhaynes** [dmippolitov/pydnsbl#8]
Running from a venv on unbuntu and flask, I have imported pycares alongside python 3.7
Previously 3.6.9 it worked fine.
Now I am getting an error:

File "/var/www/ctea/app/venv/lib/python3.7/site-packages/pydnsbl/checker.py", line 17, in
import aiodns
File "/var/www/ctea/app/venv/lib/python3.7/site-packages/aiodns/init.py", line 4, in
import pycares
File "/var/www/ctea/app/venv/lib/python3.7/site-packages/pycares/init.py", line 2, in
from ._cares import ffi as _ffi, lib as _lib
ModuleNotFoundError: No module named 'pycares._cares'

If I run python within the venv I can import pycares fine. The issue is when importing pycares from wsgi. I am not the only one with this issue:

constverum/ProxyBroker#124
constverum/ProxyBroker#157

Thanks in advance!

**Comment by CUIAk37c26Ok7** [comment]
I am also getting the same issue...what module is this supposed to be pointing to?

**Comment by dmippolitov** [comment]
Hi! It looks for me that the problem is in pycares module (aiodns dependency). Can't solve this directly. Anyway - could you provide more detailed guide how to reproduce the bug, i will take a look? 

For reference: As i can see you also started some discussion on this problem here: https://github.com/saghul/pycares/issues/127

**Comment by CUIAk37c26Ok7** [comment]
Here is what I'm getting...
![Pycares](https://user-images.githubusercontent.com/66233269/83418448-7803cd80-a3d8-11ea-9bb9-4ea4b03611bf.JPG)
